/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host , int fn , char *name ) {
	CLIENT *clnt;
	char * *result_1;
	char * add_1_arg;
	char * *result_2;
	char * search_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("%s  \n", name);
	
  add_1_arg = name;
  search_1_arg = name;
	result_1 = add_1(&add_1_arg, clnt);
	
	if (result_1 == (char **) NULL) {
		//clnt_perror (clnt, "call failed add");
	}
	
//	result_2 = search_1(&search_1_arg, clnt);
	
	if (result_2 == (char **) NULL) {
		//clnt_perror (clnt, "call failed search");
	}
	else{
	  
	  printf("el resultado fue %s "  , *result_2);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int fn;
	char *name;
	

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fn = atoi(argv[2]);
	name = argv[3];
	
	add_prog_1 (host , fn , name );
exit (0);
}
