/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
 #include <stdlib.h>
 #include <string.h>
 #define atoa(x) #x

char **
add_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	 printf("Server response to client add...%s\n" , *argp );
	 
	 ////////////////////////////////////////////
	 
	 FILE *fp;
	 fp = fopen ( "nombres.txt", "a" );
	 
	 if (fp==NULL) {fputs ("File error",stderr); exit (1);}
	 
	 /////////////////////////////////////////
	 
	 time_t t = time(NULL);
  struct tm tm = *localtime(&t);

  printf("now: %d-%d-%d %d:%d:%d\n", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday,   tm.tm_hour, tm.tm_min, tm.tm_sec);
  
  ////////////////////////////////////
  
  char *salto = "\n";
  
 char *text = *argp;
 fprintf(fp, "%s", text);//escribo el nombre
 
  fprintf(fp, "%s", salto);//escribo salto de linea
 
 fprintf(fp, "%d-%d-%d %d:%d:%d", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday,   tm.tm_hour, tm.tm_min, tm.tm_sec); //escribo la fecha
 
 fprintf(fp, "%s", salto);//escribo salto de linea

 
 fclose(fp);
	 
	 
	 
	 
	 
	 
	 
	 

	return &result;
}

char **
search_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
	 printf("Server response to client search...%s\n" , *argp );
	 
	 //leer el archivo
	 FILE * fp;
       char * line = NULL;
       int contador = 0;
       
       size_t len = 0;
       ssize_t read;

       fp = fopen("nombres.txt", "r");
       if (fp == NULL)
           exit(EXIT_FAILURE);
	 
	 while ((read = getline(&line, &len, fp)) != -1) {
           printf("Retrieved line of length %zu :\n", read);
           printf("%s", line);
           
           char *buff;
            char *s;
           buff = line;
           
           s = strstr(buff, *argp); 
           
          if (s != NULL) {
             
             printf("yaaaaaaaa %d", contador);
             contador = contador + 1 ;
             
           } 
           
           
       }
	  
	     
	     
        fclose(fp); 
	 
	 
	 
	 
	 
	result = *argp , contador;
	 
	 

	return &result;
}
